name: GPRealEstate
main: me.MrFazuku.GPR.GPRealEstate
version: 1.4.3
author: MrFazuku
depend: [GriefPrevention, Vault]

permissions:
  gprealestate.*:
    description: Gives access to all GPRealEstate permissions.
    default: op
    children:
      GPRealEstate.sell: true
      GPRealEstate.buy: true
      gprealestate.adminclaim: true
      gprealestate.sellsub: true
      gprealestate.buysub: true
  gprealestate.sell:
    description: Allows player to sell claims.
    default: true
  gprealestate.buy:
    description: Allows player to buy claims.
    default: true
  gprealestate.adminclaim:
    description: Allows players to sell admin claims.
    default: false
  gprealestate.sellsub:
    description: Allows player to sell subclaims.
    default: true
  gprealestate.buysub:
    description: Allows player to buy subclaims.
    default: true
